[package]
name = "bench_task"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils", version = "0.1" }
libc = "0.2"
rand = "0.9"
clap = { version = "4.5.24", features = ["derive"] }
